<?php

declare(strict_types=1);

use Nafiswatsiq\Subbase\Models\Feature;
use Nafiswatsiq\Subbase\Models\Plan;
use Nafiswatsiq\Subbase\Models\Subscription;
use Nafiswatsiq\Subbase\Models\SubscriptionUsage;

return [
    'default_currency' => 'USD',

    'locale_currency_map' => [
        'id' => 'IDR',
        'ms' => 'MYR',
        'my' => 'MYR',
        'sg' => 'SGD',
        'th' => 'THB',
        'ph' => 'PHP',
        'tl' => 'PHP',
        'vn' => 'VND',
        'vi' => 'VND',
        'en' => 'USD',
        'us' => 'USD',
        'gb' => 'GBP',
        'uk' => 'GBP',
        'ca' => 'CAD',
        'au' => 'AUD',
        'nz' => 'NZD',
        'ja' => 'JPY',
        'jp' => 'JPY',
        'ko' => 'KRW',
        'kr' => 'KRW',
        'zh' => 'CNY',
        'cn' => 'CNY',
        'tw' => 'TWD',
        'hk' => 'HKD',
        'in' => 'INR',
        'hi' => 'INR',
        'bn' => 'BDT',
        'de' => 'EUR',
        'fr' => 'EUR',
        'it' => 'EUR',
        'es' => 'EUR',
        'nl' => 'EUR',
        'fi' => 'EUR',
        'el' => 'EUR',
        'ch' => 'CHF',
        'ru' => 'RUB',
        'pl' => 'PLN',
        'sv' => 'SEK',
        'da' => 'DKK',
        'no' => 'NOK',
        'cs' => 'CZK',
        'hu' => 'HUF',
        'tr' => 'TRY',
        'ar' => 'SAR',
        'sa' => 'SAR',
        'ae' => 'AED',
        'za' => 'ZAR',
        'pt' => 'BRL',
        'br' => 'BRL',
        'mx' => 'MXN',
        'ar_ar' => 'ARS',
    ],

    'language_locale_map' => [
        'af' => 'Afrikaans',
        'ar' => 'Arabic',
        'az' => 'Azerbaijani',
        'be' => 'Belarusian',
        'bg' => 'Bulgarian',
        'bn' => 'Bengali',
        'bs' => 'Bosnian',
        'ca' => 'Catalan',
        'cs' => 'Czech',
        'da' => 'Danish',
        'de' => 'German',
        'el' => 'Greek',
        'en' => 'English',
        'es' => 'Spanish',
        'et' => 'Estonian',
        'fa' => 'Persian',
        'fi' => 'Finnish',
        'fr' => 'French',
        'he' => 'Hebrew',
        'hi' => 'Hindi',
        'hr' => 'Croatian',
        'hu' => 'Hungarian',
        'hy' => 'Armenian',
        'id' => 'Indonesian',
        'is' => 'Icelandic',
        'it' => 'Italian',
        'ja' => 'Japanese',
        'ka' => 'Georgian',
        'kk' => 'Kazakh',
        'ko' => 'Korean',
        'lt' => 'Lithuanian',
        'lv' => 'Latvian',
        'mk' => 'Macedonian',
        'ms' => 'Malay',
        'nb' => 'Norwegian Bokmal',
        'nl' => 'Dutch',
        'nn' => 'Norwegian Nynorsk',
        'pl' => 'Polish',
        'pt' => 'Portuguese',
        'ro' => 'Romanian',
        'ru' => 'Russian',
        'sk' => 'Slovak',
        'sl' => 'Slovenian',
        'sq' => 'Albanian',
        'sr' => 'Serbian',
        'sv' => 'Swedish',
        'th' => 'Thai',
        'tr' => 'Turkish',
        'uk' => 'Ukrainian',
        'ur' => 'Urdu',
        'uz' => 'Uzbek',
        'vi' => 'Vietnamese',
        'zh' => 'Chinese',
    ],

    'tables' => [
        'plans' => 'plans',
        'features' => 'features',
        'subscriptions' => 'subscriptions',
        'subscription_usage' => 'subscription_usage',
    ],

    'models' => [
        'user' => config('auth.providers.users.model', \App\Models\User::class),
        'plan' => Plan::class,
        'feature' => Feature::class,
        'subscription' => Subscription::class,
        'subscription_usage' => SubscriptionUsage::class,
    ],
];